CREATE TABLE loja.CLIENTE
(
    COD_CLIENTE SERIAL NOT NULL,
    NOME character varying NOT NULL,
    CPF_CNPJ character varying NOT NULL,
    EMAIL character varying NOT NULL,
    TELEFONE character varying, 
    CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_CLIENTE)
);

CREATE TABLE loja.FORNECEDOR
(
    COD_FORNECEDOR SERIAL NOT NULL,
    NOME character varying NOT NULL,
    CNPJ character varying NOT NULL,
    EMAIL character varying NOT NULL,
    TELEFONE character varying, 
    CONSTRAINT PK_FORNECEDOR PRIMARY KEY (COD_FORNECEDOR)
);


CREATE TABLE loja.PRODUTO
(
    COD_PRODUTO SERIAL NOT NULL,
    NOME character varying NOT NULL,
    DESCRICAO character varying,
    PRECO DECIMAL NOT NULL,
    DATA_CADASTRO TIMESTAMP NOT NULL, 
    CONSTRAINT PK_PRODUTO PRIMARY KEY (COD_PRODUTO)
);

CREATE TABLE loja.PRODUTO_FORNECEDOR
(
    COD_PRODUTO_FORNECEDOR SERIAL NOT NULL,
    COD_PRODUTO BIGINT NOT NULL, 
    COD_FORNECEDOR BIGINT NOT NULL,
    ESTOQUE INT NOT NULL, 
    CONSTRAINT PK_PRODUTO_FORNECEDOR PRIMARY KEY (COD_PRODUTO_FORNECEDOR),
    CONSTRAINT FK_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO),
    CONSTRAINT FK_FORNECEDOR FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDOR(COD_FORNECEDOR)
);

CREATE TABLE loja.COMPRA 
(
        COD_COMPRA SERIAL NOT NULL,
        COD_CLIENTE BIGINT NOT NULL,
        DATA_COMPRA TIMESTAMP NOT NULL,
        VALOR_COMPRA DECIMAL NOT NULL,
        CONSTRAINT PK_COMPRA PRIMARY KEY (COD_COMPRA),
        CONSTRAINT FK_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE)

);

CREATE TABLE loja.PRODUTO_COMPRA 
(
        COD_PRODUTO_COMPRA SERIAL NOT NULL,
        COD_PRODUTO BIGINT NOT NULL,
        COD_COMPRA BIGINT NOT NULL,
        QT_PRODUTO INT NOT NULL, 
        CONSTRAINT PK_PRODUTO_COMPRA PRIMARY KEY (COD_PRODUTO_COMPRA),
        CONSTRAINT FK_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO),
        CONSTRAINT FK_COMPRA FOREIGN KEY (COD_COMPRA) REFERENCES COMPRA(COD_COMPRA)
        
);

CREATE TABLE loja.ESTADO (
        COD_ESTADO SERIAL NOT NULL,
        NOME character varying NOT NULL,
        SIGLA character varying NOT NULL,
        CONSTRAINT PK_ESTADO PRIMARY KEY (COD_ESTADO)
);

CREATE TABLE loja.ENDERECO_CLIENTE (
        COD_ENDERECO SERIAL NOT NULL,
        COD_CLIENTE BIGINT NOT NULL,
        COD_ESTADO INT NOT NULL,
        NOME_RUA character varying,
        CIDADE character varying NOT NULL,
        NUMERO INT NOT NULL,
        CEP character varying NOT NULL,
        COMPLEMENTO  character varying,
        CONSTRAINT PK_ENDERECO PRIMARY KEY (COD_ENDERECO),
        CONSTRAINT FK_ESTADO FOREIGN KEY (COD_ESTADO) REFERENCES ESTADO(COD_ESTADO), 
        CONSTRAINT FK_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE)
);

CREATE TABLE loja.CARTAO (
        COD_CARTAO SERIAL NOT NULL,
        COD_CLIENTE BIGINT NOT NULL,
        NUMERO character varying NOT NULL,
        NOME character varying NOT NULL,
        COD_OPERACAO INT NOT NULL,
        CODIGO_SEG character varying NOT NULL,
        VALIDADE TIMESTAMP NOT NULL,
        CONSTRAINT PK_CARTAO PRIMARY KEY (COD_CARTAO),
        CONSTRAINT FK_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE),
        CONSTRAINT FK_TIPO_OPERACAO FOREIGN KEY (COD_OPERACAO) REFERENCES TIPO_OPERACAO(COD_OPERACAO)
);

CREATE TABLE loja.TIPO_OPERACAO (
        COD_OPERACAO SERIAL NOT NULL,
        DESCRICAO character varying NOT NULL,
        CONSTRAINT PK_OPERACAO PRIMARY KEY (COD_OPERACAO)
);

CREATE TABLE loja.ENDERECO_FORNECEDOR (
        COD_ENDERECO_FORNECEDOR SERIAL NOT NULL,
        COD_FORNECEDOR BIGINT NOT NULL,
        COD_ESTADO INT NOT NULL,
        NOME_RUA character varying,
        CIDADE character varying NOT NULL,
        NUMERO INT NOT NULL,
        CEP character varying NOT NULL,
        COMPLEMENTO  character varying,
        CONSTRAINT PK_ENDERECO_FORNECEDOR PRIMARY KEY (COD_ENDERECO_FORNECEDOR),
        CONSTRAINT FK_ESTADO FOREIGN KEY (COD_ESTADO) REFERENCES ESTADO(COD_ESTADO), 
        CONSTRAINT FK_FORNECEDOR FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDOR(COD_FORNECEDOR)
);

INSERT INTO estado (nome, sigla) 
VALUES
('Acre', 'AC'),
('Alagoas', 'AL'),
('Amazonas', 'AM'),
('Amapá', 'AP'),
('Bahia', 'BA' ),
('Ceará', 'CE'),
('Distrito Federal', 'DF'),
('Espírito Santo', 'ES'),
('Goiás', 'GO'),
('Maranhão', 'MA'),
('Minas Gerais', 'MG'),
('Mato Grosso do Sul', 'MS'),
('Mato Grosso', 'MT'),
('Pará', 'PA'),
('Paraíba', 'PB'),
('Pernambuco', 'PE'),
('Piauí', 'PI'),
('Paraná', 'PR'),
('Rio de Janeiro', 'RJ'),
('Rio Grande do Norte', 'RN'),
('Rondônia', 'RO'),
('Roraima', 'RR'),
('Rio Grande do Sul', 'RS'),
('Santa Catarina', 'SC'),
('Sergipe', 'SE'),
('São Paulo', 'SP'),
('Tocantins', 'TO');

SELECT * FROM ESTADO;

INSERT INTO TIPO_OPERACAO (descricao)
VALUES ('Crédito'),
('Débito'),
('Crédito e débito');




SELECT SUM(PR_FO.ESTOQUE) estoque, PR.COD_PRODUTO,  
nome, preco, descricao, DATA_CADASTRO dataCadastro 
FROM PRODUTO_FORNECEDOR PR_FO 
INNER JOIN PRODUTO PR ON PR.COD_PRODUTO = PR_FO.COD_PRODUTO 
-- WHERE PR.COD_PRODUTO = 15
GROUP BY PR.COD_PRODUTO;


SELECT FO.nome, FO.cnpj, FO.email, FO.telefone, FO.COD_FORNECEDOR, estoque 
FROM PRODUTO_FORNECEDOR PR_FO 
INNER JOIN PRODUTO PR ON PR.COD_PRODUTO = PR_FO.COD_PRODUTO 
INNER JOIN FORNECEDOR FO ON FO.COD_FORNECEDOR = PR_FO.COD_FORNECEDOR 
WHERE PR.COD_PRODUTO = 16;

SELECT FO.nome, FO.cnpj, FO.email, FO.telefone, FO.COD_FORNECEDOR, estoque 
FROM PRODUTO_FORNECEDOR PR_FO 
INNER JOIN PRODUTO PR ON PR.COD_PRODUTO = PR_FO.COD_PRODUTO 
INNER JOIN FORNECEDOR FO ON FO.COD_FORNECEDOR = PR_FO.COD_FORNECEDOR;

SELECT * FROM CLIENTE;

INSERT INTO CLIENTE (NOME, CPF_CNPJ, EMAIL, TELEFONE) 
VALUES 
('Cliente 1', '11111111111', 'cliente_um@email.com', '123456789'), 
('Cliente 2', '22222222222', 'cliente_dois@email.com', '123456789'),
('Cliente 3', '33333333333', 'cliente_tres@email.com', '123456789');

SELECT * FROM COMPRA;

INSERT INTO COMPRA (COD_CLIENTE, DATA_COMPRA, VALOR_COMPRA) 
VALUES 
(1, '2022-06-12 20:13:00.000', 100.00),
(2, '2022-06-13 20:13:00.000', 150.00),
(3, '2022-06-15 20:13:00.000', 200.00);

SELECT * FROM PRODUTO_COMPRA;

INSERT INTO PRODUTO_COMPRA (COD_PRODUTO, COD_COMPRA, QT_PRODUTO) 
VALUES
(16, 5, 2);

